config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :giftlists

      resources :categories

      resources :my_wishes

      resources :stores

      resources :gifts

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "gifts#index"
  resources :giftlists
  resources :categories
  resources :my_wishes
  resources :stores
  resources :gifts
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/store.rb
require "open-uri"
class Store < ApplicationRecord
  before_validation :geocode_address

  def geocode_address
    if address.present?
      url = "https://maps.googleapis.com/maps/api/geocode/json?key=#{ENV['GMAP_API_KEY']}&address=#{URI.encode(address)}"

      raw_data = open(url).read

      parsed_data = JSON.parse(raw_data)

      if parsed_data["results"].present?
        self.address_latitude = parsed_data["results"][0]["geometry"]["location"]["lat"]

        self.address_longitude = parsed_data["results"][0]["geometry"]["location"]["lng"]

        self.address_formatted_address = parsed_data["results"][0]["formatted_address"]
      end
    end
  end
  # Direct associations

  has_many   :gifts,
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :address, presence: true

  validates :phone_number, uniqueness: true

  validates :phone_number, presence: true

  validates :store_name, uniqueness: true

  validates :store_name, presence: true

  # Scopes

  def to_s
    store_name
  end
end

app/controllers/api/v1/stores_controller.rb
class Api::V1::StoresController < Api::V1::GraphitiController
  def index
    stores = StoreResource.all(params)
    respond_with(stores)
  end

  def show
    store = StoreResource.find(params)
    respond_with(store)
  end

  def create
    store = StoreResource.build(params)

    if store.save
      render jsonapi: store, status: :created
    else
      render jsonapi_errors: store
    end
  end

  def update
    store = StoreResource.find(params)

    if store.update_attributes
      render jsonapi: store
    else
      render jsonapi_errors: store
    end
  end

  def destroy
    store = StoreResource.find(params)

    if store.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: store
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[show edit update destroy]

  def index
    @q = Store.ransack(params[:q])
    @stores = @q.result(distinct: true).includes(:gifts).page(params[:page]).per(10)
    @location_hash = Gmaps4rails.build_markers(@stores.where.not(address_latitude: nil)) do |store, marker|
      marker.lat store.address_latitude
      marker.lng store.address_longitude
    end
  end

  def show
    @gift = Gift.new
  end

  def new
    @store = Store.new
  end

  def edit; end

  def create
    @store = Store.new(store_params)

    if @store.save
      redirect_to @store, notice: "Store was successfully created."
    else
      render :new
    end
  end

  def update
    if @store.update(store_params)
      redirect_to @store, notice: "Store was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_url, notice: "Store was successfully destroyed."
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:store_name, :address, :phone_number)
  end
end

app/views/stores/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Store #<%= store.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Store name</dt>
      <dd><%= store.store_name %></dd>

      <dt>Address</dt>
      <dd>
        <div>
          <%= render partial: "stores/one_photo_map" %>
        </div>
      </dd>

      <dt>Phone number</dt>
      <dd><%= store.phone_number %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back store, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_store_url(store), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to store, method: :delete, data: { confirm: "Do you really want to delete this store?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(store.updated_at) %> ago
  </div>
</div>

app/views/stores/_form.html.erb
<% was_validated = store.errors.any? %>

<%= form_with(model: store, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% store_name_class = "form-control" %>
    <% store_name_was_invalid = store.errors.include?(:store_name) %>

    <% if was_validated %>
      <% if store_name_was_invalid %>
        <% store_name_class << " is-invalid" %>
      <% else %>
        <% store_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :store_name %>
    <%= f.text_field :store_name, class: store_name_class, placeholder: "Enter store name" %>
    <% if store_name_was_invalid %>
      <% store.errors.full_messages_for(:store_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% address_class = "form-control" %>
    <% address_was_invalid = store.errors.include?(:address) %>

    <% if was_validated %>
      <% if address_was_invalid %>
        <% address_class << " is-invalid" %>
      <% else %>
        <% address_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :address %>
    <%= f.text_field :address, class: address_class, placeholder: "Enter address" %>
    <% if address_was_invalid %>
      <% store.errors.full_messages_for(:address).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% phone_number_class = "form-control" %>
    <% phone_number_was_invalid = store.errors.include?(:phone_number) %>

    <% if was_validated %>
      <% if phone_number_was_invalid %>
        <% phone_number_class << " is-invalid" %>
      <% else %>
        <% phone_number_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: phone_number_class, placeholder: "Enter phone number" %>
    <% if phone_number_was_invalid %>
      <% store.errors.full_messages_for(:phone_number).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/stores/_list_item.html.erb
<%= link_to store, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= store %>
    <small class="text-muted">
      <%= time_ago_in_words(store.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/stores/_one_photo_map.html.erb
<div id="location_map" style="height: 480px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'location_map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @store.address_latitude %>,
        "lng": <%= @store.address_longitude %>,
        "infowindow": "<h5><%= @store.created_at %></h5><small><%= @store.address_formatted_address %></small>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/stores/_store_gifts.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Gifts

    <a data-toggle="collapse" href="#store_gifts_new_form">
      Add gift
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @store.gifts.each do |gift| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to gift, gift %>

        <%= link_to gift, method: :delete, data: { confirm: "Do you really want to delete this gift" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="store_gifts_new_form">
        <%= render partial: "stores/store_gifts_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/stores/_store_gifts_new_form.html.erb
<%= form_with(model: @gift, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :gift_name %>

    <%= f.text_field :gift_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :photo %>

    <%= f.file_field :photo, class: "form-control" %>
  </div>

  <%= f.hidden_field :store_id, value: @store.id %>

  <div class="form-group">
    <%= f.label :category_id %>

    <%= f.collection_select :category_id, Category.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>

    <%= f.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>

    <%= f.text_field :website, class: "form-control" %>
  </div>

  <%= f.submit "Create gift", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/stores/_stores_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "stores_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :store_name_cont, "Store name contains" %>
    <%= f.text_field :store_name_cont, :class => "form-control", :placeholder => "Store name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number_cont, "Phone number contains" %>
    <%= f.text_field :phone_number_cont, :class => "form-control", :placeholder => "Phone number contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :gifts_gift_name_cont, "Gifts gift_name contains" %>
    <%= f.text_field :gifts_gift_name_cont, :class => "form-control", :placeholder => "Gifts gift_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/stores" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#stores_filters">
  Show filters
</a>

app/views/stores/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Store #<%= @store.id %>
      </h2>

      <div class="card-body">
        <%= render "form", store: @store %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Stores

      <%= link_to new_store_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "stores/stores_search_form" %>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render partial: "stores/all_photos_map" %>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Stores

        <%= link_to new_store_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @stores, partial: "list_item", as: :store %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @stores, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/stores/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Store
      </h2>

      <div class="card-body">
        <%= render "form", store: @store %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @store, partial: "card", as: :store %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "stores/store_gifts" %>
  </div>
</div>