config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :giftlists

      resources :categories

      resources :my_wishes

      resources :stores

      resources :gifts

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "gifts#index"
  resources :giftlists
  resources :categories
  resources :my_wishes
  resources :stores
  resources :gifts
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/giftlist.rb
class Giftlist < ApplicationRecord
  # Direct associations

  belongs_to :gift

  belongs_to :user

  # Indirect associations

  # Validations

  validates :friend_name, presence: true

  validates :gift_id, presence: true

  validates :user_id, presence: true

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/giftlists_controller.rb
class Api::V1::GiftlistsController < Api::V1::GraphitiController
  def index
    giftlists = GiftlistResource.all(params)
    respond_with(giftlists)
  end

  def show
    giftlist = GiftlistResource.find(params)
    respond_with(giftlist)
  end

  def create
    giftlist = GiftlistResource.build(params)

    if giftlist.save
      render jsonapi: giftlist, status: :created
    else
      render jsonapi_errors: giftlist
    end
  end

  def update
    giftlist = GiftlistResource.find(params)

    if giftlist.update_attributes
      render jsonapi: giftlist
    else
      render jsonapi_errors: giftlist
    end
  end

  def destroy
    giftlist = GiftlistResource.find(params)

    if giftlist.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: giftlist
    end
  end
end

app/controllers/giftlists_controller.rb
class GiftlistsController < ApplicationController
  before_action :set_giftlist, only: %i[show edit update destroy]

  def index
    @q = Giftlist.ransack(params[:q])
    @giftlists = @q.result(distinct: true).includes(:user,
                                                    :gift).page(params[:page]).per(10)
  end

  def show; end

  def new
    @giftlist = Giftlist.new
  end

  def edit; end

  def create
    @giftlist = Giftlist.new(giftlist_params)

    if @giftlist.save
      message = "Giftlist was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @giftlist, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @giftlist.update(giftlist_params)
      redirect_to @giftlist, notice: "Giftlist was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @giftlist.destroy
    message = "Giftlist was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to giftlists_url, notice: message
    end
  end

  private

  def set_giftlist
    @giftlist = Giftlist.find(params[:id])
  end

  def giftlist_params
    params.require(:giftlist).permit(:user_id, :friend_name, :gift_id)
  end
end

app/views/giftlists/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Giftlist #<%= giftlist.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @giftlist.user.present? %>
          <%= link_to giftlist.user, giftlist.user %>
        <% end %>
      </dd>

      <dt>Friend name</dt>
      <dd><%= giftlist.friend_name %></dd>

      <dt>Gift</dt>
      <dd>
        <% if @giftlist.gift.present? %>
          <%= link_to giftlist.gift, giftlist.gift %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back giftlist, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_giftlist_url(giftlist), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to giftlist, method: :delete, data: { confirm: "Do you really want to delete this giftlist?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(giftlist.updated_at) %> ago
  </div>
</div>

app/views/giftlists/_form.html.erb
<% was_validated = giftlist.errors.any? %>

<%= form_with(model: giftlist, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = giftlist.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% giftlist.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% friend_name_class = "form-control" %>
    <% friend_name_was_invalid = giftlist.errors.include?(:friend_name) %>

    <% if was_validated %>
      <% if friend_name_was_invalid %>
        <% friend_name_class << " is-invalid" %>
      <% else %>
        <% friend_name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :friend_name %>
    <%= f.text_field :friend_name, class: friend_name_class, placeholder: "Enter friend name" %>
    <% if friend_name_was_invalid %>
      <% giftlist.errors.full_messages_for(:friend_name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% gift_class = "form-control" %>
    <% gift_was_invalid = giftlist.errors.include?(:gift) %>

    <% if was_validated %>
      <% if gift_was_invalid %>
        <% gift_class << " is-invalid" %>
      <% else %>
        <% gift_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :gift_id %>
    <%= f.collection_select :gift_id, Gift.all, :id, :to_s, {}, class: "form-control" %>
    <% if gift_was_invalid %>
      <% giftlist.errors.full_messages_for(:gift).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/giftlists/_giftlists_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "giftlists_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :friend_name_cont, "Friend name contains" %>
    <%= f.text_field :friend_name_cont, :class => "form-control", :placeholder => "Friend name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "User Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='usergteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at greater than or equal to", :data => {:target => '#usergteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#usergteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='userlteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :user_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "User Created at less than or equal to", :data => {:target => '#userlteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#userlteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#usergteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#userlteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#usergteqcreated_atPicker').on("dp.change", function (e) {
              $('#userlteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#userlteqcreated_atPicker').on("dp.change", function (e) {
              $('#usergteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :gift_gift_name_cont, "Gift gift_name contains" %>
    <%= f.text_field :gift_gift_name_cont, :class => "form-control", :placeholder => "Gift gift_name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/giftlists" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#giftlists_filters">
  Show filters
</a>

app/views/giftlists/_list_item.html.erb
<%= link_to giftlist, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= giftlist %>
    <small class="text-muted">
      <%= time_ago_in_words(giftlist.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/giftlists/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Giftlist #<%= @giftlist.id %>
      </h2>

      <div class="card-body">
        <%= render "form", giftlist: @giftlist %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/giftlists/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Giftlists

      <%= link_to new_giftlist_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "giftlists/giftlists_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Giftlists

        <%= link_to new_giftlist_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @giftlists, partial: "list_item", as: :giftlist %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @giftlists, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/giftlists/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Giftlist
      </h2>

      <div class="card-body">
        <%= render "form", giftlist: @giftlist %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/giftlists/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @giftlist, partial: "card", as: :giftlist %>
  </div>
</div>